version: "3.8"
services:
  next-google-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    ports:
      - 3000:3000
    networks:
      - internal-apps
networks:
  internal-apps:
    external: true
